<?php
namespace Anar\Core;

use WP_Error;

class Image_Downloader{

    private $size_limit;
    private $timeout;
    private $retry_limit;
    private $current_product_id_for_upload = null; // Added property

    public function __construct($size_limit = 5 * 1024 * 1024, $timeout = 60, $retry_limit = 2){
        $this->size_limit = $size_limit;
        $this->timeout = $timeout;
        $this->retry_limit = $retry_limit;
    }

    /**
     * Download an image from a URL and insert it into the WordPress media library.
     *
     * @param string $image_url The URL of the image to download.
     * @param int $product_id The ID of the product to attach the image to.
     * @return int|WP_Error The attachment ID on success, or a WP_Error on failure.
     */
    public function save_image_as_attachment($image_url, int $product_id) {
        $existing_attachment_id = $this->is_image_downloaded($image_url, $product_id);
        if ($existing_attachment_id) {
            awca_log("Image #{$existing_attachment_id} downloaded before, so skipp download again and use it.");
            return $existing_attachment_id;
        }

        // Transform the image URL if needed
        $image_url = $this->transform_image_url($image_url);

        // Get the image file name from the URL
        $image_name = basename($image_url);

        // Get the WordPress upload directory
        // We get the default here, but will filter it later
        $upload_dir = wp_upload_dir();

        $response = $this->fetch_image($image_url);
        if (is_wp_error($response)) {
            return $response;
        }

        // Get the HTTP response code and image data
        $http_code = wp_remote_retrieve_response_code($response);
        $image_data = wp_remote_retrieve_body($response);

        // Check for invalid response or large file size
        $content_length = wp_remote_retrieve_header($response, 'content-length');
        if ($http_code !== 200 || empty($image_data) || ($this->size_limit > 0 && $content_length > $this->size_limit)) { // Check size limit only if > 0
            awca_log("Failed to download image from URL: $image_url");
            awca_log("HTTP Code: $http_code");
            if ($this->size_limit > 0 && $content_length > $this->size_limit) {
                awca_log("Image file larger than ".($this->size_limit/(1024*1024))."MB: $content_length bytes");
            }
            return new WP_Error('image_download_failed', __('Failed to download image.'));
        }

        // Determine the filename (use unique filename function later within the filter context if needed)
        $image_name = basename(parse_url($image_url, PHP_URL_PATH)); // Get filename from path
        $image_name = sanitize_file_name($image_name); // Sanitize

        // Temporarily store product ID and add the filter
        $this->current_product_id_for_upload = $product_id;
        add_filter('upload_dir', [$this, '_custom_upload_dir']);

        $attachment_id = new WP_Error('filter_error', 'Initial state before try block.'); // Default error

        try {
            // Note: wp_unique_filename needs the target directory, which our filter provides.
            // We let wp_insert_attachment handle the file saving and unique naming within the filtered directory.

            // Prepare the attachment data array (file path is determined by wp_insert_attachment using the filtered upload_dir)
            $attachment_data = array(
                // 'guid' will be generated by wp_insert_attachment based on the final path
                'post_mime_type' => wp_check_filetype($image_name, null)['type'], // Basic mime type check based on name
                'post_title'     => preg_replace('/\.[^.]+$/', '', $image_name), // Title from filename without extension
                'post_content'   => '',
                'post_status'    => 'inherit'
            );

            // Let WordPress handle the upload and attachment creation using the filtered directory
            // We need to sideload the image data instead of providing a file path directly
            // Ensure required functions are loaded
            require_once(ABSPATH . 'wp-admin/includes/file.php');
            require_once(ABSPATH . 'wp-admin/includes/media.php');
            require_once(ABSPATH . 'wp-admin/includes/image.php');

            // Create a temporary file to sideload
            $tmp = download_url($image_url, $this->timeout);
            $file_array = array();

            if (is_wp_error($tmp)) {
                @unlink($tmp); // Delete temp file if created
                awca_log("Failed to download image to temporary file: " . $tmp->get_error_message());
                return $tmp; // Return WP_Error from download_url
            }

            // Set up the file array for media_handle_sideload
            preg_match('/[^\?]+\.(jpg|jpe|jpeg|gif|png)\b/i', $image_url, $matches);
            $file_array['name'] = $image_name ?: basename($matches[0]); // Use original name or derive from URL
            $file_array['tmp_name'] = $tmp;


            // Sideload the image - this uses wp_insert_attachment internally and respects our filter
            $attachment_id = media_handle_sideload($file_array, $product_id, $attachment_data['post_title'], $attachment_data);

            // Check for errors during sideloading
            if (is_wp_error($attachment_id)) {
                @unlink($file_array['tmp_name']); // Delete temp file
                awca_log("Failed to sideload image: " . $attachment_id->get_error_message());
                // Return the WP_Error object
            } else {
                 // Mark this image URL as downloaded only on success
                $this->mark_image_as_downloaded($image_url, $product_id, $attachment_id);
                awca_log("image #{$attachment_id} uploaded - Product #{$product_id}");
            }

        } catch (\Exception $e) {
             awca_log("Exception during image saving for product #{$product_id}: " . $e->getMessage(), 'error');
             $attachment_id = new WP_Error('image_save_exception', $e->getMessage());
        } finally {
            // Always remove the filter and clear the temporary property
            remove_filter('upload_dir', [$this, '_custom_upload_dir']);
            $this->current_product_id_for_upload = null;
            // Clean up temp file if it still exists and there was an error
             if (isset($file_array['tmp_name']) && file_exists($file_array['tmp_name'])) {
                 @unlink($file_array['tmp_name']);
             }
        }

        return $attachment_id; // Return attachment ID or WP_Error
    }

    /**
     * Download an image from a URL, insert it into the media library, and set it as the product's featured image.
     *
     * @param int $product_id The ID of the product to set the image for.
     * @param string $image_url The URL of the image to download.
     * @return int|WP_Error The attachment ID on success, or a WP_Error on failure.
     */
    public function set_product_thumbnail($product_id, $image_url) {
        // Insert the attachment into the WordPress media library
        $attachment_id = $this->save_image_as_attachment($image_url, $product_id);

        // Check if there was an error in downloading and inserting the image
        if (is_wp_error($attachment_id)) {
            awca_log("Failed to download and insert attachment for product ID: $product_id. Error: " . $attachment_id->get_error_message());
            // Clean this meta to skip from cron job check
            delete_post_meta($product_id, '_product_image_url', false);
            return $attachment_id;
        }

        // Set the downloaded image as the product's featured image
        $thumbnail_result = set_post_thumbnail($product_id, $attachment_id);

        if (!$thumbnail_result) {
            awca_log("Failed to set product thumbnail for product ID: $product_id");
            // Clean this meta to skip from cron job check
            delete_post_meta($product_id, '_product_image_url', false);
            return new WP_Error('thumbnail_set_failed', __('Failed to set product thumbnail.'));
        }

        // Clean this meta to skip from cron job check
        delete_post_meta($product_id, '_product_image_url', false);
        awca_log('Product #'.$product_id.' thumbnail is set');
        return $attachment_id;
    }

    /**
     * Set product gallery images from array of image URLs
     *
     * @param int   $product_id         Product ID
     * @param array $image_urls         Array of image URLs
     * @param int   $gallery_image_limit Maximum number of images to use
     * @return array|WP_Error Array of attachment IDs or WP_Error
     */
    public function set_product_gallery($product_id, $image_urls, $gallery_image_limit = 5) {
        if (!is_array($image_urls) || empty($image_urls)) {
            awca_log("No valid image URLs provided for product ID: $product_id", 'warning');
            return new \WP_Error('invalid_image_urls', __('No valid image URLs provided.'));
        }

        if (!$product_id || !is_numeric($product_id)) {
            awca_log("Invalid product ID provided: $product_id", 'error');
            return new \WP_Error('invalid_product_id', __('Invalid product ID provided.'));
        }

        // Check if product exists
        $product = wc_get_product($product_id);
        if (!$product) {
            awca_log("Product not found with ID: $product_id", 'error');
            return new \WP_Error('product_not_found', __('Product not found.'));
        }

        $attachment_ids = [];
        $successful_downloads = 0;
        $failed_downloads = 0;

        // Limit the number of images to process
        $image_urls = array_slice($image_urls, 0, $gallery_image_limit);

        foreach ($image_urls as $image_url) {
            // Validate URL
            if (empty($image_url) || !filter_var($image_url, FILTER_VALIDATE_URL)) {
                awca_log("Invalid image URL for product ID: $product_id. URL: $image_url", 'warning');
                $failed_downloads++;
                continue; // Skip this URL but continue processing others
            }

            try {
                // Download and upload the image
                $attachment_id = $this->save_image_as_attachment($image_url, $product_id);

                if (is_wp_error($attachment_id)) {
                    awca_log(
                        "Failed to download image for product ID: $product_id. URL: $image_url. Error: " .
                        $attachment_id->get_error_message(),
                        'error'
                    );
                    $failed_downloads++;
                    continue; // Skip this URL but continue processing others
                }

                $attachment_ids[] = $attachment_id;
                $successful_downloads++;

            } catch (\Exception $e) {
                awca_log(
                    "Exception while processing image for product ID: $product_id. URL: $image_url. Error: " .
                    $e->getMessage(),
                    'error'
                );
                $failed_downloads++;
                continue; // Skip this URL but continue processing others
            }
        }

        // Set product gallery images if there are attachment IDs
        if (!empty($attachment_ids)) {
            try {
                // Merge with existing gallery images if needed
                // Uncomment the below lines if you want to keep existing gallery images
                // $existing_gallery_ids = $product->get_gallery_image_ids();
                // $attachment_ids = array_merge($existing_gallery_ids, $attachment_ids);

                $product->set_gallery_image_ids($attachment_ids);
                $product->save();

                awca_log(
                    "Product #$product_id gallery updated successfully. " .
                    "Added: $successful_downloads images. Failed: $failed_downloads images.",
                    'info'
                );

                return [
                    'attachment_ids' => $attachment_ids,
                    'successful' => $successful_downloads,
                    'failed' => $failed_downloads
                ];

            } catch (\Exception $e) {
                awca_log(
                    "Failed to update gallery for product ID: $product_id. Error: " . $e->getMessage(),
                    'error'
                );
                return new \WP_Error(
                    'gallery_update_failed',
                    __('Failed to update product gallery.'),
                    [
                        'product_id' => $product_id,
                        'error_message' => $e->getMessage(),
                        'attachment_ids' => $attachment_ids
                    ]
                );
            }
        } else {
            $status = $failed_downloads > 0 ? 'All downloads failed' : 'No images to process';
            awca_log("$status for product ID: $product_id", 'warning');
            return new \WP_Error(
                'no_gallery_images',
                __('No gallery images were successfully downloaded.'),
                [
                    'product_id' => $product_id,
                    'failed_downloads' => $failed_downloads
                ]
            );
        }
    }

    /**
     * Check if the URL starts with the expected prefix.
     * @param string $url
     * @return string Transformed URL.
     */
    public function transform_image_url($url) {
        $prefix = "https://s3.c22.wtf/";
        if (strpos($url, $prefix) === 0) {
            // Replace the initial part of the URL and add the new prefix.
            $new_prefix = "https://s3.anar360.com/_img/width_1024/https://s3.anar360.com/";
            return str_replace($prefix, $new_prefix, $url);
        } else {
            // If the URL does not match the expected pattern, return it unchanged.
            return $url;
        }
    }


    /**
     * Attempt to fetch an image from a URL with retries.
     *
     * @param string $image_url The URL of the image to fetch.
     * @return array|WP_Error Array containing the response, or a WP_Error on failure.
     */
    private function fetch_image($image_url) {
        $attempts = 0;

        while ($attempts < $this->retry_limit) {
            $response = wp_remote_get($image_url, array(
                'timeout'     => $this->timeout,
                'redirection' => 10,
                'sslverify'   => false,  // Add this line to disable SSL verification (use with caution)
            ));

            if (!is_wp_error($response)) {
                return $response;
            }

            $attempts++;
            awca_log("Retrying download for URL: $image_url. Attempt #$attempts");
        }

        awca_log("Failed to download image from URL after $this->retry_limit attempts: $image_url");
        return new WP_Error('image_download_failed', __('Failed to download image after several attempts.'));
    }


    /**
     * Check if an image has already been downloaded.
     * @param string $image_url The URL of the image.
     * @param int $product_id The ID of the product.
     * @return int|false The attachment ID if the image is already downloaded, false otherwise.
     */
    private function is_image_downloaded($image_url, $product_id) {
        $downloaded = get_post_meta($product_id, '_awca_downloaded_images', true);
        if (is_array($downloaded)) {
            foreach ($downloaded as $entry) {
                if ($entry['url'] === $image_url) {
                    return $entry['attachment_id'];
                }
            }
        }
        return false;
    }

    /**
     * Mark an image URL as downloaded.
     * @param string $image_url The URL of the image.
     * @param int $product_id The ID of the product.
     * @param int $attachment_id The ID of the attachment.
     */
    private function mark_image_as_downloaded($image_url, $product_id, $attachment_id) {
        $downloaded = get_post_meta($product_id, '_awca_downloaded_images', true);
        if (!is_array($downloaded)) {
            $downloaded = array();
        }
        $downloaded[] = array(
            'url' => $image_url,
            'attachment_id' => $attachment_id
        );
        update_post_meta($product_id, '_awca_downloaded_images', $downloaded);
    }

    /**
     * Filter for wp_upload_dir to change the upload path.
     *
     * @param array $uploads Array of upload directory data.
     * @return array Modified array of upload directory data.
     */
    public function _custom_upload_dir($uploads) {
        // Check if we have a product ID context
        if ($this->current_product_id_for_upload === null) {
            return $uploads; // Do nothing if not called within our specific context
        }

        // Define the base folder for these imports
        $import_folder = 'anar-products';

        // Create a subdirectory based on the product ID (e.g., last two digits)
        // This creates 100 potential subfolders (00-99)
        $sub_folder = sprintf('%02d', $this->current_product_id_for_upload % 100);

        // Construct the new subdirectory path relative to the uploads folder
        $new_subdir = '/' . $import_folder . '/' . $sub_folder;

        // Prevent recursion if the filter is somehow applied again
        if (strpos($uploads['subdir'], $import_folder) === false) {
            $uploads['subdir'] = $new_subdir;
            $uploads['path'] = $uploads['basedir'] . $new_subdir;
            $uploads['url'] = $uploads['baseurl'] . $new_subdir;

             // Ensure the target directory exists. wp_mkdir_p is recursive.
            if (!file_exists($uploads['path'])) {
                wp_mkdir_p($uploads['path']);
            }
        }

        return $uploads;
    }

}


